
name: cuid
description: cuid is a library for generating unique collision-resistant IDs optimized for horizontal scaling and performance
version: 1.0.0-nullsafety.0
author: Levi Cook <levicook@gmail.com>
homepage: https://github.com/levicook/cuid

dev_dependencies:
  test: ^1.6.4

environment:
  sdk: '>=2.12.0 <3.0.0'
